import React from 'react';
import { WorldStats as WorldStatsType } from '../types';
import { Globe, TrendingUp, Users, Wind, Info } from 'lucide-react';
import clsx from 'clsx';

interface Props {
  stats: WorldStatsType;
  pu: number;
  tu: number;
}

const StatItem = ({ icon: Icon, label, value, colorClass, tooltip }: { icon: any, label: string, value: number, colorClass: string, tooltip: string }) => (
  <div className="group relative flex items-center space-x-2 bg-slate-900/50 px-3 py-1.5 rounded border border-slate-800 cursor-help">
    <Icon size={16} className={colorClass} />
    <div className="flex flex-col">
      <span className="text-[10px] uppercase text-slate-500 font-bold tracking-wider">{label}</span>
      <span className={clsx("text-sm font-mono font-medium", colorClass)}>
        {value.toFixed(1)}%
      </span>
    </div>
    
    {/* Tooltip */}
    <div className="absolute top-full left-1/2 -translate-x-1/2 mt-2 w-48 bg-slate-800 border border-slate-700 p-2 rounded shadow-xl text-[10px] text-slate-300 pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity z-50">
        {tooltip}
    </div>
  </div>
);

export const WorldStats: React.FC<Props> = ({ stats, pu, tu }) => {
  return (
    <div className="h-16 border-b border-slate-800 bg-slate-950 flex items-center justify-between px-6 shrink-0 z-10 relative shadow-md">
      <div className="flex items-center space-x-6">
        <div className="flex items-center space-x-2">
          <div className="w-8 h-8 bg-emerald-500/10 rounded flex items-center justify-center border border-emerald-500/20">
            <Globe size={18} className="text-emerald-400" />
          </div>
          <div>
            <h1 className="text-sm font-bold text-slate-100 tracking-tight">THE ANALYST</h1>
            <p className="text-[10px] text-slate-500">v1.0.4-rc</p>
          </div>
        </div>
        
        <div className="h-8 w-px bg-slate-800 mx-2" />

        <div className="flex space-x-3">
            <StatItem 
                icon={TrendingUp} 
                label="Economy" 
                value={stats.economy} 
                colorClass={stats.economy > 60 ? "text-emerald-400" : stats.economy < 40 ? "text-red-400" : "text-amber-400"} 
                tooltip="Global Market Health. Increases with True Understanding (TU). Crashes if Trust is low."
            />
            <StatItem 
                icon={Users} 
                label="Trust" 
                value={stats.socialTrust} 
                colorClass="text-blue-400" 
                tooltip="Social Trust. Decreases when you use invasive tracking or have data breaches. Affects data quality."
            />
            <StatItem 
                icon={Wind} 
                label="Entropy" 
                value={stats.entropy} 
                colorClass={stats.entropy > 50 ? "text-red-400" : "text-slate-400"} 
                tooltip="System Chaos. Rises when Observability is low (<50%) or Perceived Understanding exceeds True Understanding by > 50x."
            />
        </div>
      </div>

      <div className="flex items-center space-x-6">
         <div className="text-right group relative cursor-help">
            <div className="text-[10px] uppercase text-slate-500 tracking-wider flex items-center justify-end gap-1">True Understanding <Info size={10} /></div>
            <div className="text-sm font-mono text-indigo-300">{tu.toFixed(2)}</div>
            <div className="absolute top-full right-0 mt-2 w-64 bg-slate-800 border border-slate-700 p-3 rounded shadow-xl text-[10px] text-slate-300 pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity z-50 text-right">
                Generated by high-quality Metrics (Quality &gt; 15%) and deployed AI Models. Represents actual value delivered.
            </div>
         </div>
         <div className="text-right group relative cursor-help">
            <div className="text-[10px] uppercase text-slate-500 tracking-wider flex items-center justify-end gap-1">Perceived Understanding <Info size={10} /></div>
            <div className="text-xl font-mono text-emerald-400 font-bold">{Math.floor(pu).toLocaleString()}</div>
            <div className="absolute top-full right-0 mt-2 w-64 bg-slate-800 border border-slate-700 p-3 rounded shadow-xl text-[10px] text-slate-300 pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity z-50 text-right">
                Your score/currency. Generated by Metrics, Dashboards, and Marketing. If this exceeds True Understanding by too much (50x), Entropy rises.
            </div>
         </div>
      </div>
    </div>
  );
};